name: Test Bot (No Upload, Download Only)

on:
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg imagemagick
        sudo sed -i 's/rights="none"/rights="read|write"/' /etc/ImageMagick-6/policy.xml

    - name: Install Python Libraries
      run: |
        pip install --upgrade pip
        pip install moviepy==1.0.3 edge-tts gtts numpy Pillow==9.5.0 imageio-ffmpeg

    - name: Run Video Bot
      run: |
        python bot.py

    - name: 📥 Upload Video For Download
      uses: actions/upload-artifact@v4
      with:
        name: My-Test-Video
        path: output/FINAL_UPLOAD.mp4
